service: url-shortener
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: python3.9
  stage: live
  region: us-east-1

package:
  patterns:
    - 'main.py'
    - '!node_modules/**'

functions:
  urlShortener:
    name: url-shortener
    handler: main.api_handler
    memorySize: 256
    timeout: 29

    events:
      - httpApi:
          path: '/status'
          method: GET
      - httpApi:
          path: '/{param}'
          method: GET

    layers:
      - Ref: PythonRequirementsLambdaLayer

custom:
  customDomain:
    domainName: short.kellenanker.com
    basePath: ''
    stage: live
    createRoute53Record: true
    certificateName: '*.kellenanker.com'
    autoDomain: true
    autoDomainWaitFor: 300
    endpointType: regional
    securityPolicy: tls_1_2
    apiType: http

  pythonRequirements:
    layer: true

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
