service: url-shortener
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: python3.9
  stage: live
  region: us-east-1
  httpApi:
    disableDefaultEndpoint: true
    cors:
      allowedOrigins:
        - 'https://url-shortener.kellenanker.com'
        - 'http://localhost:3000'
      allowedHeaders: '*'
      allowCredentials: false
      maxAge: 300

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:Query
            - dynamodb:Scan
          Resource:
            - !GetAtt UrlTable.Arn

package:
  patterns:
    - 'main.py'
    - '!node_modules/**'

functions:
  urlShortener:
    name: url-shortener
    handler: main.api_handler
    memorySize: 256
    timeout: 29

    environment:
      DOMAIN_NAME: '${self:custom.customDomain.domainName}'
      DDB_TABLE: !Ref UrlTable

    events:
      # Shorten
      - httpApi:
          path: '/'
          method: POST
      # Metrics
      - httpApi:
          path: '/'
          method: GET
      # Redirect
      - httpApi:
          path: '/{param}'
          method: GET

    layers:
      - Ref: PythonRequirementsLambdaLayer

custom:
  domainName: kell.link

  customDomain:
    domainName: ${self:custom.domainName}
    basePath: ''
    stage: live
    createRoute53Record: true
    certificateName: ${self:custom.domainName}
    autoDomain: true
    autoDomainWaitFor: 300
    endpointType: regional
    securityPolicy: tls_1_2
    apiType: http

  customCertificate:
    certificateName: ${self:custom.domainName}
    hostedZoneNames: ${self:custom.domainName}.

  pythonRequirements:
    layer: true

plugins:
  - serverless-python-requirements
  - serverless-domain-manager
  - serverless-certificate-creator

resources:
  Resources:
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: url-shortener
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: N
          - AttributeName: CreateTime
            AttributeType: N
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
          - AttributeName: CreateTime
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: False
