service: url-shortener
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: python3.9
  stage: live
  region: us-east-1
  logs:
    httpApi: true
  httpApi:
    disableDefaultEndpoint: true

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem*
            - dynamodb:PutItem*
          Resource:
            - !GetAtt UrlTable.Arn

package:
  patterns:
    - 'main.py'
    - '!node_modules/**'

functions:
  urlShortener:
    name: url-shortener
    handler: main.api_handler
    memorySize: 256
    timeout: 29

    environment:
      PYTHONHASHSEED: 0
      DOMAIN_NAME: "${self:custom.customDomain.domainName}"

    events:
      # Shorten
      - httpApi:
          path: '/'
          method: POST
      # Metrics
      - httpApi:
          path: '/'
          method: GET
      # Redirect
      - httpApi:
          path: '/{param}'
          method: GET

    layers:
      - Ref: PythonRequirementsLambdaLayer

custom:
  customDomain:
    domainName: short.kellenanker.com
    basePath: ''
    stage: live
    createRoute53Record: true
    certificateName: '*.kellenanker.com'
    autoDomain: true
    autoDomainWaitFor: 300
    endpointType: regional
    securityPolicy: tls_1_2
    apiType: http

  pythonRequirements:
    layer: true

plugins:
  - serverless-python-requirements
  - serverless-domain-manager

resources:
  Resources:
    UrlTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: url-shortener
        AttributeDefinitions:
          - AttributeName: ShortUrlId
            AttributeType: S
        KeySchema:
          - AttributeName: ShortUrlId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: TTL
          Enabled: False
